language: bash
services: docker

arch:
  - arm64
  - amd64

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
script:
  - travis_retry docker build -t "hitch:latest" .
  - ~/official-images/test/run.sh "hitch:latest"

after_script:
  - docker images
