#!/bin/sh
set -e

# only add --config=... if was set and not empty
ARG_CONF="${HITCH_CONFIG_FILE-/etc/hitch/hitch.conf}"
if [ -n "${ARG_CONF}" ]; then
	ARG_CONF=--config="${ARG_CONF}"
fi

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- hitch "${ARG_CONF}" "$@"
fi

exec "$@"
